jobs:
- job: 'Build'
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    projectRoot: 'src'
    artifactName: 'fe-ng-artifact'   
    outputPath: './out'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      cd '$(System.DefaultWorkingDirectory)/angular-test-fe'
      npm install -g @angular/cli
      npm install
      ng build --configuration production
    displayName: 'npm install and build'

  - bash: |
      ls -la '$(System.DefaultWorkingDirectory)/angular-test-fe/dist/angular-test-fe/*'
      mkdir '$(outputPath)'
      cp -R '$(System.DefaultWorkingDirectory)/angular-test-fe/dist/angular-test-fe/*' '$(outputPath)'
    displayName: Copy published files
  #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

  - bash: |
      cat > Dockerfile << EOF
      FROM nginx:latest
      WORKDIR /usr/share/nginx/html
      ADD '$(outputPath)' ./
      EXPOSE 80
      EOF
    displayName: Create Dockerfile

  # - template: fe-publish-steps.yaml
  - template: fe-docker-build-steps.yaml