jobs:
- job: 'Build'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      ng build $(Build.Repository.Name) --configuration production --output-path='$(Build.ArtifactStagingDirectory)'
    displayName: 'npm install and build'
    workingDirectory: $(System.DefaultWorkingDirectory)/$(Build.Repository.Name)

  - template: fe-publish-steps.yaml
  - template: fe-docker-build-steps.yaml