jobs:
- job: 'Build'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: |
      apt-get install curl
      curl -fsSL https://deb.nodesource.com/setup_18.x | -E bash 
      apt-get install -y nodejs
    displayName: 'install nodejs'

  - script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
    displayName: 'npm install and build'

  - template: fe-publish-steps.yaml