jobs:
- job: 'Build'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
      npm run build:prod
    displayName: 'npm install and build'

  - template: fe-publish-steps.yaml
  - template: fe-docker-build-steps.yaml