trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- template: fe-publish-steps.yaml